### PR TITLE
Release 1.0.36

### PR DESCRIPTION
**Pull request by TheLastCicada**

### CODE REVIEW

**Review by wwills2 — APPROVED** [review]

**Comment by heldermmrod** [comment]
Hi guys,

I'm Hélder Rodrigues, from Portugal. I work in the Portuguese Energy Agency and we are tasked with implementing the Portuguese Voluntary Carbon Market.

Sorry that I'm reaching out to you guys like this if there's a more appropriate forum for this, let me know (I've tried to get in touch with the World Bank but got no answer).

After some research, I bumped into these repositories and all the support information from World Band.

We want to use this open-source code to build our registry. However, we need to launch a public tender to hire the software development company we'll work with. 

Given this, we were thinking about asking the tender respondents to implement these packages and provide us with a link to access them, to ensure they're ability and experience.

I'd love for you guys to comment on the above information, but the actual question I have for you is, how long do you think an experienced team takes to implement (Tokenization Engine + Core Registry UI + Core Registry API)? Because if this takes longer than 2/3 days, then it is unreasonable to ask for this.

@TheLastCicada 

Kind Regards,
Hélder Rodrigues

**Comment by hoffmang9** [comment]
@heldermmrod We will have someone from the Chia Network team reach out shortly.

**Comment by hoffmang9** [comment]
Also, if you shoot an email to hello@chia.net then we can get back to you via email as well.

**Comment by sbooth1440** [comment]
@heldermmrod - My name is Steve Booth.  I head our Solutions group here at Chia and work closely with both the Core Registry and also The World Bank.  My email address is s.booth@chia.net.  If you would like to email me directly we would be happy to hop on a quick call and address your questions.  Thanks!  Steve

**Pull request merged**
